# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM walki12/jupyternotebook

#Install nbGrader and extentions
RUN pip install nbgrader
RUN jupyter nbextension install --sys-prefix --py nbgrader --overwrite
RUN jupyter nbextension enable --sys-prefix --py nbgrader
RUN jupyter serverextension enable --sys-prefix --py nbgrader
